### ISSUE TITLE
Facebook Pixel.

### ISSUE THREAD

**Issue by raziraz** [krig-collective/krig.io#18] opened 2018-02-25 13:43 UTC
Add the Facebook Pixel integration to enable target marketing.

**Comment by jaweglin** [comment] 2018-02-28 10:31
I have added the pixel code, but left to do is for it to intergrate with the facebook page after launch.

**Comment by Johannestegner** [comment] 2018-03-03 12:02
Where is the pixel code located? Is it the facebook tracking code that we currently have in the postcookie.js file? In that case, the code loads as intended now and we can close this issue imho.

**Closed as completed** 2018-03-07 09:39 UTC
Labels: to-do
